[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
cmds = ["echo 'Installing dependencies...'"]

[start]
cmd = "bash -c 'echo \"client_max_body_size 500M; client_body_timeout 600s; client_header_timeout 600s;\" > /etc/nginx/conf.d/uploads.conf && nginx -g \"daemon off;\" & php-fpm'"

[variables]
NIXPACKS_NGINX_CLIENT_MAX_BODY_SIZE = "500M"
